let word3 = "wow JavaScript is so cool";
let firstWord3 = word3.substring(0, 3);
let secondWord3 = word3.substring(4, 14);
let thirdWord3 = word3.substring(15, 17);
let fourthword3 = word3.substring(18, 20);
let fifthword3 = word3.substring(21, 25);
console.log("First Word: " + firstWord3);
console.log("Second Word: " + secondWord3);
console.log("Third Word: " + thirdWord3);
console.log("Fourth Word: " + fourthword3);
console.log("Fifth Word: " + fifthword3);
