let word3 = 'wow JavaScript is so cool';
let exampleFirstWord3 = word3.substring(0, 3);
let secondword3 = word3.substring(4, 14);
let thirdword3 = word3.substring(15, 17);
let fourthword3 = word3.substring(18, 20);
let fifthword3 = word3.substring(21, 25);
console.log('First Word: ' + exampleFirstWord3);
console.log('secondword3: ' + secondword3);
console.log('thirdword3: ' + thirdword3);
console.log('fourthword3: ' + fourthword3);
console.log('fifthword3: ' + fifthword3);