let word4 = "wow JavaScript is so cool";
let exampleFirstWord4 = word4.substring(0, 3);
let exampleSecondWord4 = word4.substring(4, 14);
let exampleThirdWord4 = word4.substring(15, 17);
let exampleFourthWord4 = word4.substring(18, 20);
let exampleFifthWord4 = word4.substring(21, 25);
let firstWordLength = exampleFirstWord4.length;
let secondWordLength = exampleSecondWord4.length;
let thirdWordLength = exampleThirdWord4.length;
let fourthWordLength = exampleFourthWord4.length;
let fifthWordLength = exampleFifthWord4.length;
console.log(`First Word: ${exampleFirstWord4}, length: ${firstWordLength} `);
console.log(`Second Word:${exampleSecondWord4}, length: ${secondWordLength}`);
console.log(`Third Word: ${exampleThirdWord4}, length: ${thirdWordLength}`);
console.log(`Fourth Word: ${exampleFourthWord4}, length: ${fourthWordLength}`);
console.log(`Fifth Word: ${exampleFifthWord4}, length: ${fifthWordLength}`);
